server:
  port: 8005
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: root
    url: jdbc:mysql://192.172.0.5:3306/woniu_his?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
  rabbitmq:
    host: 192.172.0.5
    port: 5672
    username: xj
    password: 123
    virtual-host: /xj
    publisher-confirm-type: correlated
    publisher-returns: true
  redis:
    port: 6379
    host: 192.172.0.5
  #hystrix的超时时间
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 4000  #设置feign超时连接时长
        readTimeout: 4000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
          strategy: SEMAPHORE
        timeout:
          enabled: true
#  #ribbon的超时时间
#  ribbon:
#    ReadTimeout: 30000
#    ConnectTimeout: 30000
knife4j:
  enable: true
logging:
  level:
    com.woniu.cg.dao: DEBUG

